name: Linux build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-binary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install required depencies
      run: |
       sudo apt update
       sudo apt install libhidapi-dev
       sudo apt install libhidapi-hidraw0
       sudo apt install pkg-config
       sudo apt install libgtk-3-dev
       sudo apt install libxml2-utils
       sudo apt install dfu-programmer
    - name: Build
      working-directory: src
      run: make
    #- name: make check
      #run: make check
    #- name: make distcheck
      #run: make distcheck
